'use client';

import { useEffect, useState } from 'react';
import { createClient } from '../../../lib/supabase-browser';

export default function Scanner(){const [programmes,setProgrammes]=useState<any[]>([]);const [programme,setProgramme]=useState('');const [token,setToken]=useState('');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);
useEffect(()=>{(async()=>{const s=createClient();const {data:u}=await s.auth.getUser();if(!u.user){window.location.href='/login';return;}const {data:m}=await s.from('memberships').select('organisation_id,role').eq('user_id',u.user.id);const b=(m??[]).find((x:any)=>['owner','admin','business_admin','staff'].includes(x.role));if(!b)return;const {data:p}=await s.from('loyalty_programmes').select('id,name,stamps_required,reward_name').eq('organisation_id',b.organisation_id).eq('active',true);setProgrammes(p??[]);if(p?.[0])setProgramme(p[0].id);})();},[]);
async function issue(){setBusy(true);setMessage('');const s=createClient();const {data,error}=await s.rpc('issue_loyalty_stamp',{p_programme_id:programme,p_customer_qr:token.trim(),p_quantity:1});if(error)setMessage(error.message);else setMessage(`Stamp added. Customer now has ${data.stamps}/${data.stamps_required} stamps.${data.reward_created?' 🎁 Reward unlocked!':''}`);setBusy(false);}
return <main><header className="topbar"><div className="logo">Messy<span>Turtule</span></div><a className="btn secondary" href="/business">Back</a></header><div className="container" style={{maxWidth:700}}><section className="section"><div className="eyebrow">Business scanner</div><h1>Add a customer stamp</h1><p className="lead">Select the programme and scan the customer's universal QR. Camera scanning is the next hardware enhancement; this version also accepts the QR token directly for testing.</p><div className="card"><label>Programme<select value={programme} onChange={e=>setProgramme(e.target.value)}>{programmes.map((p:any)=><option key={p.id} value={p.id}>{p.name} · {p.stamps_required} stamps → {p.reward_name}</option>)}</select></label><label>Customer QR token<input value={token} onChange={e=>setToken(e.target.value)} placeholder="Paste the scanned QR value" /></label><button className="btn primary" disabled={!programme||!token.trim()||busy} onClick={issue}>{busy?'Adding…':'Add 1 stamp'}</button>{message&&<p style={{marginBottom:0}}>{message}</p>}</div></section></div></main>}
