'use client';

import { FormEvent, useState } from 'react';
import { createClient } from '../../../../lib/supabase-browser';

export default function NewProgramme() {
  const [name,setName]=useState(''); const [description,setDescription]=useState(''); const [stamps,setStamps]=useState(10); const [reward,setReward]=useState('Free reward'); const [saving,setSaving]=useState(false); const [error,setError]=useState('');
  async function submit(e:FormEvent){e.preventDefault();setSaving(true);setError('');const s=createClient();const {data:u}=await s.auth.getUser();if(!u.user){window.location.href='/login';return;}const {data:m}=await s.from('memberships').select('organisation_id,role').eq('user_id',u.user.id);const b=(m??[]).find((x:any)=>['owner','admin','business_admin'].includes(x.role));if(!b){setError('Business admin access required.');setSaving(false);return;}const {error}=await s.from('loyalty_programmes').insert({organisation_id:b.organisation_id,name,description,stamps_required:stamps,reward_name:reward,active:true}).select('id').single();if(error)setError(error.message);else window.location.href='/business';setSaving(false);}
  return <main><header className="topbar"><div className="logo">Messy<span>Turtule</span></div><a className="btn secondary" href="/business">Back</a></header><div className="container" style={{maxWidth:760}}><section className="section"><div className="eyebrow">Business console</div><h1>Create a loyalty programme</h1><p className="lead">Keep it simple: collect stamps, then give customers a reward.</p><form className="card" onSubmit={submit}><label>Programme name<input required value={name} onChange={e=>setName(e.target.value)} placeholder="Coffee Club" /></label><label>Description<textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="Buy a coffee, collect a stamp." /></label><label>Stamps required<input required min={1} max={100} type="number" value={stamps} onChange={e=>setStamps(Number(e.target.value))} /></label><label>Reward<input required value={reward} onChange={e=>setReward(e.target.value)} placeholder="Free coffee" /></label>{error&&<p>{error}</p>}<button className="btn primary" disabled={saving}>{saving?'Creating…':'Create programme'}</button></form></section></div></main>;
}
