'use client';

import { FormEvent, useState } from 'react';
import { createClient } from '../../lib/supabase-browser';

export default function LoginPage() {
  const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [mode,setMode]=useState<'login'|'signup'>('login'); const [message,setMessage]=useState(''); const [loading,setLoading]=useState(false);
  async function submit(e:FormEvent){e.preventDefault();setLoading(true);setMessage('');const supabase=createClient();const result=mode==='login'?await supabase.auth.signInWithPassword({email,password}):await supabase.auth.signUp({email,password});setLoading(false);if(result.error){setMessage(result.error.message);return;}window.location.href='/dashboard';}
  return <main className="container" style={{maxWidth:520,paddingTop:70}}><div className="card"><div className="logo">Messy<span>Turtule</span></div><div className="eyebrow" style={{marginTop:30}}>{mode==='login'?'Welcome back':'Join the movement'}</div><h1 style={{fontSize:48,letterSpacing:-3}}>{mode==='login'?'Your loyalty awaits.':'One account. Everything.'}</h1><p className="meta" style={{fontSize:16,marginBottom:28}}>{mode==='login'?'Sign in to see your programmes, progress and rewards.':'Create one account for all your loyalty cards.'}</p><form onSubmit={submit}><label>Email</label><input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/><label>Password</label><input required minLength={6} type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="••••••••"/><button className="btn primary" disabled={loading} style={{width:'100%',marginTop:8}}>{loading?'Please wait…':mode==='login'?'Sign in →':'Create account →'}</button></form>{message&&<p style={{marginTop:16,color:'var(--accent)'}}>{message}</p>}<button className="btn secondary" onClick={()=>setMode(mode==='login'?'signup':'login')} style={{width:'100%',marginTop:10}}>{mode==='login'?'Create a new account':'I already have an account'}</button><p className="meta" style={{textAlign:'center',marginTop:22}}>By continuing, you agree to use MessyTurtule responsibly.</p></div></main>;
}
